pipeline{
  agent any
  environment {
	AC_KEY = credentials('AWS_ACCESS_KEY')
	SEC_KEY = credentials('AWS_SECRET_KEY')

}
 
  stages {
   stage("Opening"){
         steps{
            //Welcome message
            script{
               sh "cowsay welcome"
               sh "echo 'Welcome to Jenkins'"
}
}
}

   stage("Workspace_cleanup"){
        //Cleaning WorkSpace
        steps{
            step([$class: 'WsCleanup'])
}
}

   stage("Repo_clone"){
       //Clone repo from GitHub
      steps {
         checkout ([$class: 'GitSCM', branches: [[name: '*/master']], userRemoteConfigs: [[credentialsId: 'jenkins', url: ''git@github.com:Vikas-Tamboli/master.git]]])

}
}
   stage("terraform_init"){
     //terraform init
     steps{
      script{
       sh '''
         cowsay terraform init
         cd ..
         cd infra
         bash plugins.sh $AC_KEY $SEC_KEY
         cd -
       '''
}
}
}

   stage("static_analysis"){
     //static analysis
       
     
       steps{
       script{
       sh '''
            cowsay static_analysis
            cd ..
            cd infra
            terraform validate 
            cd -
       '''
}
}
}

}
}
